[project]
name = "test-ecmwf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.7"
dependencies = ['selenium','fastapi','uvicorn[standard]','python-multipart']
